services:
  - type: web
    name: ptt-ticket-alert-bot
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
